### ISSUE TITLE
[TA, XR맵 인터랙션] 기믹 에셋 크기 및 위치 조정 2 

### ISSUE THREAD

**Issue by h27480suhyeon** [LovelySejong/MTVS3_3rd_Unreal#103]
- [x] 문제방 3-2에 있는 액자 크기와 위치 맞추기 
(액자를 비추는 조명이 있어서 제 B맵의 동일한 크기와 위치의 액자 배치가 필요합니다. 아래와 같이 값을 맞춰 다시 배치해주시면 감사하겠습니다)

<액자틀>
Location | x : 226, y : 1579, z: 224.75
Rotation | x : 0, y: 90, z: 0
Scale | x : 2.2 , y: 3.96, z : 2.45
------------------------------------------------
<그림>
Location | x : 225.24, y: 1583.09, z : 218.18
Rotation | x : 116.56, y: -90, z : -26.56
Scale | x : 1.4, y: 2.06, z: 0.45
-----------------------------------------------
<네게껍 글자>
Location | x : 224.02, y : 1584.72, z : 225.6
Rotation | x : 90, y : 0, z: 0
Scale | x : 1.6, y: 1.4, z : 0.6

<img width="515" alt="image" src="https://github.com/user-attachments/assets/da09b68e-724a-488d-a292-4fa1d05adcee">

- [x] 문제방 3-2 옷장 종이 크기 비율 맞추기
Scale ( 0.47, 0.67, 0.6 )
<img width="776" alt="image" src="https://github.com/user-attachments/assets/99c76c9f-5554-47de-80ea-1ba809e1ae6a">

- [x] 문제방 4 버튼 크기 맞추기
Scale ( 0.03, 0.03, 0.03)
<img width="473" alt="image" src="https://github.com/user-attachments/assets/0f163d27-27ac-4c89-b6a3-42e2d23adbc8">

**Comment by sunwchoi** [comment]
확인했습니다
