### ISSUE TITLE
문제방2 UI Problem4, Problem8 5번 문항 삭제 요청

### ISSUE THREAD

**Issue by g0r0kke** [LovelySejong/MTVS3_3rd_Unreal#37]
4지선다 문제여야 하는데 5번 문항을 잘못 추가해드렸습니다.
문제방2 문제 중 Problem4와 Problem8은 5번 문항 없애고 4번 문항까지로 다시 제작해주시면 감사드리겠습니다.
(언리얼 같은 경로에 같은 이름으로 저장하면 파일 덮어쓰기가 가능하니 이렇게 해주시면 좋을 것 같아요.)
수정 후 close 바랍니다.

![image](https://github.com/user-attachments/assets/c4996b28-bf7a-4f4d-9a28-44dc91a4dd60)
![image](https://github.com/user-attachments/assets/4692a221-dc9d-47be-a98d-268af7c4290c)

![image](https://github.com/user-attachments/assets/1462152d-53b1-40ee-ba92-6472c51da8b6)

**Comment by minjunkim5876** [comment]
네 확인했습니다.

2024년 9월 10일 (화) 오후 6:51, g0r0kke ***@***.***>님이 작성:

**Comment by minjunkim5876** [comment]
수정완료입니다.
