### ISSUE TITLE
[TA] 프로토 이슈 체크리스트

### ISSUE THREAD

**Issue by g0r0kke** [LovelySejong/MTVS3_3rd_Unreal#38]
* 체크리스트에 체크 가능합니다.
* 모두 완료되면 Close 해주세요.

## 문제방1
- [x] 비밀번호 버튼 텍스쳐링(또는 모델링) -> 0~9, ❌ 아이콘,  엔터↩️ 아이콘
- [x] 각자 문제 정답이 상대 방의 정답인 것 연출 -> ex) 박스, 비밀번호 패드에 상대 문양 새기기

## 문제방2
- [ ] 각자 문제 정답이 상대 방의 정답인 것 연출 -> ex) 천장 텍스쳐 배경을 상대 방의 색깔로 표시/천장 텍스쳐 안에 상대 문양 새기기 등
- [x] 컬러 다이얼 노란색/주황색 더 구분되도록 색 바꿀지 결정
- [x] 천장 색깔(흰색) - 컬러 다이얼 색깔 매치

## 문제방3
- [x] 문제방3 개인 카페트 에셋
- [x] 컵 색깔 바꾸기, XR에 레버 정답 전달

## 문제방4
- [x] TV
- [x] 달력 등 바닥에 두고 플레이어가 돌릴 오브젝트 선정
- [x] #43

**Comment by minjunkim5876** [comment]
넵 확인했습니다.

**Comment by h27480suhyeon** [comment]
@g0r0kke  고등어 통짜로 쓰기엔 기획 상 많이 어긋날까요? 고등어 외부 어셋 자체를 반으로 잘라 사용할 때 안쪽 텍스쳐가 없기 때문에 새로 모델링을 해야하는데 고등어 구조상 상당히 오래걸릴 것으로 예상됩니다.
