### ISSUE TITLE
PlayLevel (프로토레벨) 수정사항

### ISSUE THREAD

**Issue by h27480suhyeon** [LovelySejong/MTVS3_3rd_Unreal#44]
PSH 폴더 B2_Map을 참고하시고 에셋 크기와 위치를 맞춰주시면 감사하겠습니다.
https://denim-jelly-ca9.notion.site/a57bcc433a2b41bf9af1b405e664ee71?pvs=4

## 문제방1
- [x] 키패드 크기 줄이기 
--------------------- 

## 문제방2
- [x] 컬러 다이얼 크기 키우기

## 문제방3
- [x] PSH B2_Map을 참고하여 액자 그림 색상 맞추기 (3-1에는 파란색 그림, 3-2에는 핑크색 그림)
- [x] 액자 글자 검정색 글씨로 바꾸기 (psh 폴더에 검정색 글씨 색으로 바꾼 material 있습니다, 기존 decal이 색이 잘 안보여서 제 쪽에서 바꿨어요!)

**Comment by sunwchoi** [comment]
확인했습니다
