### ISSUE TITLE
효과음 추가 관련

### ISSUE THREAD

**Issue by g0r0kke** [LovelySejong/MTVS3_3rd_Unreal#68]
비밀번호 키패드 누르는 소리 & 컬러 다이얼 돌리는 소리 & 문 열리는 소리
(+ 문제방4 TV 화면 넘기는 효과음, 천장 창문 열릴 때 소리)
이런 효과음들 추가해줄 수 있어?

bgm이랑 카페트 올라가고 내려가는 소리는 내가 찾아볼게

**Comment by sunwchoi** [comment]
확인했습니다
