### ISSUE TITLE
[문제방2] 천장 데칼 위치&박스 ui 수정사항

### ISSUE THREAD

**Issue by g0r0kke** [LovelySejong/MTVS3_3rd_Unreal#69]
* 파란색 ui가 잘려 있어서 옆으로 위치 조정 필요
* 박스 돌리는 ui에서 상대 문양 데칼이 안 보여서 수정 필요
![image](https://github.com/user-attachments/assets/cdecaee9-13a1-4b9c-997a-08b648987065)
![image](https://github.com/user-attachments/assets/98a4a729-fab0-45b0-bde2-cba5d61f8a10)

**Comment by sunwchoi** [comment]
확인했습니다
