### ISSUE TITLE
[TA, XR맵 인터랙션] 기믹 에셋 크기 및 위치 조정 등

### ISSUE THREAD

**Issue by h27480suhyeon** [LovelySejong/MTVS3_3rd_Unreal#94]
- [x] 문제방 4 키패드 위치 사진과 같이 조정하기
<img width="317" alt="스크린샷 2024-09-23 181211" src="https://github.com/user-attachments/assets/665a8dba-bfa5-424f-9fcd-f4959ee3e40a">

- [x]  튜토리얼 방 일반 레버 크기 조절 (작게 하기)
<img width="347" alt="image" src="https://github.com/user-attachments/assets/62f524d1-80d1-46d2-997e-65d8077c0698">

- [x] 문제방 1 사진과 같이 박스 크기 조절 ( 작게 하기)
<img width="559" alt="image" src="https://github.com/user-attachments/assets/19a95978-47a4-458b-ac6b-9f1ae28be1f8">

**Comment by sunwchoi** [comment]
확인했습니다
