### ISSUE TITLE
[TA] 음성 채팅 키 데칼 추가 필요

### ISSUE THREAD

**Issue by g0r0kke** [LovelySejong/MTVS3_3rd_Unreal#95]
Q 누르면 음성 채팅이 가능하게 하려고 하는데
Q->🎙️ 이런 느낌의 데칼 만들어서 튜토리얼방 적당한 위치에 배치해줄 수 있을까?

![image](https://github.com/user-attachments/assets/ec165f8f-ac98-4a96-a941-141b7bae2568)

**Comment by h27480suhyeon** [comment]
오케이 ~~
